var lan_en = {
    help:"help",
    welcome: "Welcome!",
    spotify1: "Ecco qui la tua richiesta!",
    spotify2: "Here is your request song!",
    spotify3: "Here is the song of the requested artist!",
    spotify4: "Here is a playlist of songs of the requested genre!",
    spotify5: "Here is a playlist of songs recommended according to your mood",
    spotify6: "Here is a recommended song based on your mood",
    spotify7: "Here is a recommended song that you might like",
    video: "here is yur video",
    why: "why",
    explain: "explain",

  change:"change",
  another:"another",
  another2:"another one",
  another3:"read me another one",
  another4:"give me another one",
  another5:"read other",
  another6:"read another news",
  change1:"change song",
  change2:"change track",
  change3:"another track",
  change4:"change video",
  change5:"give me another video",
  change6:"give me another track",
  change7:"give me another song",
  change8:"change music",
  change9:"change news",
 inscity: "insert city",
 satisfy:"are you satisfied about the answer?",
   yes:"yes",
   donotunderstand :" I do not understand what you mean. Try asking your question with other words!",
   register: "In order to use the other functions, you must register with Myrror at the following address",
    retry:'try again',
    unfor:'unfortunately',
    unfor2:'unfortunately',
    unfor3:'Unfortunately no data are available for the indicated period',
    login1:'For this function you must login'
}

var lan_it = {
  help:"aiuto",
    welcome: "Ciao",
    spotify1: "Ecco qui la tua richiesta!",
    spotify2: "Ecco qui la canzone richiesta!",
    spotify3: "Ecco qui la canzone dell'artista richiesto!",
    spotify4: "Ecco una playlist di canzoni del genere richiesto!",
    spotify5: "Ecco qui una playlist di canzoni raccomandata in base al tuo umore",
    spotify6: "Ecco qui un brano consigliato in base al tuo umore",
    spotify7: "Ecco qui un brano consigliato che potrebbe piacerti",
      video1: "Ecco qui il video richiesto",
      why: "perchè",
    explain: "spiega",
  
    change:"cambia",
  another:"cambio",
  another2:"dammi un'altra",
  another3:"leggi un'altra",
  another4:"dammene un'altra",
  another5:"leggine un'altra",
  another6:"leggi altra news",
  change1:"altra canzone",
  change2:"dimmi un'altra",
  change3:"riproducine un'altra",
  change4:"cambia video",
  change5:"fammi vedere un altro",
  change6:"dammi un altro",
  change7:"altro video",
  change8:"altra canzone",
  change9:"altra news",
   inscity: "Inserisci la città",
    satisfy:"sei soddisfatto della risposta?",
    yes:"si",
    donotunderstand : "Non ho capito cosa vuoi dire. Prova a riformulare la tua domanda!",
    register: "Per poter sfruttare le altre funzioni, occorre registrarsi a Myrror al seguente indirizzo",
    retry:'riprova',
    unfor:'sfortunatamente',
    unfor2:'purtroppo',
    unfor3:'Sfortunatamente non sono disponibili dati riguardanti il periodo indicato',
    login1:'Per questa funzione occorre effettuare il login'
      
}



